In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\rrama\OneDrive\Desktop\Python code\mckinsey.csv")

In [3]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [4]:
df.head(3)

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df ["country"]

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     1704 non-null   object
 1   year        1704 non-null   int64
 2   population  1704 non-null   int64
 3   continent   1704 non-null   object
 4   life_exp    1704 non-null   float64
 5   gdp_cap     1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB

In [8]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [9]:
df.tail(20)

       country  year  population continent  life_exp      gdp_cap
1684    Zambia  1972     4506497    Africa    50.107  1773.498265
1685    Zambia  1977     5216550    Africa    51.386  1588.688299
1686    Zambia  1982     6100407    Africa    51.821  1408.678565
1687    Zambia  1987     7272406    Africa    50.821  1213.315116
1688    Zambia  1992     8381163    Africa    46.100  1210.884633
1689    Zambia  1997     9417789    Africa    40.238  1071.353818
1690    Zambia  2002    10595811    Africa    39.193  1071.613938
1691    Zambia  2007    11746035    Africa    42.384  1271.211593
1692  Zimbabwe  1952     3080907    Africa    48.451   406.884115
1693  Zimbabwe  1957     3646340    Africa    50.469   518.764268
1694  Zimbabwe  1962     4277736    Africa    52.358   527.272182
1695  Zimbabwe  1967     4995432    Africa    53.995   569.795071
1696  Zimbabwe  1972     5861135    Africa    55.635   799.362176
1697  Zimbabwe  1977     6642107    Africa    57.674   685.587682
1698  Zimbabwe  1982     7636524    Africa    60.363   788.855041
1699  Zimbabwe  1987     9216418    Africa    62.351   706.157306
1700  Zimbabwe  1992    10704340    Africa    60.377   693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809   792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989   672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487   469.709298

In [10]:
df.shape

(1704, 6)

In [11]:
df.tail(15)

       country  year  population continent  life_exp      gdp_cap
1689    Zambia  1997     9417789    Africa    40.238  1071.353818
1690    Zambia  2002    10595811    Africa    39.193  1071.613938
1691    Zambia  2007    11746035    Africa    42.384  1271.211593
1692  Zimbabwe  1952     3080907    Africa    48.451   406.884115
1693  Zimbabwe  1957     3646340    Africa    50.469   518.764268
1694  Zimbabwe  1962     4277736    Africa    52.358   527.272182
1695  Zimbabwe  1967     4995432    Africa    53.995   569.795071
1696  Zimbabwe  1972     5861135    Africa    55.635   799.362176
1697  Zimbabwe  1977     6642107    Africa    57.674   685.587682
1698  Zimbabwe  1982     7636524    Africa    60.363   788.855041
1699  Zimbabwe  1987     9216418    Africa    62.351   706.157306
1700  Zimbabwe  1992    10704340    Africa    60.377   693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809   792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989   672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487   469.709298

In [12]:
pd.DataFrame([['Afghanistan',1952, 8425333, 'Asia', 28.801, 779.445314 ],
 ['Afghanistan',1957, 9240934, 'Asia', 30.332, 820.853030 ],
 ['Afghanistan',1962, 102267083, 'Asia', 31.997, 853.100710 ]],
 columns=['country','year','population','continent','life_exp','gdp_cap'])

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962   102267083      Asia    31.997  853.100710

In [13]:

pd.DataFrame([['Afghanistan',1952, 8425333, 'Asia', 28.801, 779.445314 ]],
 columns=['country','year','population','continent','life_exp','gdp_cap'])

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314

In [14]:
pd.DataFrame({'country':['Afghanistan', 'Afghanistan'], 'year':[1952,1957],
 'population':[842533, 9240934], 'continent':['Asia', 'Asia'],
 'life_exp':[28.801, 30.332], 'gdp_cap':[779.44, 820.853030]})

       country  year  population continent  life_exp    gdp_cap
0  Afghanistan  1952      842533      Asia    28.801  779.44000
1  Afghanistan  1957     9240934      Asia    30.332  820.85303

In [15]:
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [16]:
df.keys

<bound method NDFrame.keys of           country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]>

In [17]:
df['country'].head()

0    Afghanistan
1    Afghanistan
2    Afghanistan
3    Afghanistan
4    Afghanistan
Name: country, dtype: object

In [18]:
df[['country','year']].head()

       country  year
0  Afghanistan  1952
1  Afghanistan  1957
2  Afghanistan  1962
3  Afghanistan  1967
4  Afghanistan  1972

In [19]:
df['country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
       'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Czech Republic',
       'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia',
       'Finland', 'France', 'Gabon', 'Gambia', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti',
       'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea, Dem. Rep.',
       'Korea, Rep.', 'Kuwait', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Madagascar', 'Malawi', 'Malaysia', 'Mali', 'Mauritania',
       'Mauritius', 'Mexico', 'Mongolia', 'Montenegro', 'Morocco',
       'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman',
       'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Puerto Rico', 'Reunion', 'Romania', 'Rwanda',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia',
       'Somalia', 'South Africa', 'Spain', 'Sri Lanka', 'Sudan',
       'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tanzania', 'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Uganda', 'United Kingdom', 'United States', 'Uruguay',
       'Venezuela', 'Vietnam', 'West Bank and Gaza', 'Yemen, Rep.',
       'Zambia', 'Zimbabwe'], dtype=object)

In [20]:
df['country'].value_counts()

country
Afghanistan           12
Albania               12
Algeria               12
Angola                12
Argentina             12
                      ..
Vietnam               12
West Bank and Gaza    12
Yemen, Rep.           12
Zambia                12
Zimbabwe              12
Name: count, Length: 142, dtype: int64

In [21]:
type(df)

pandas.core.frame.DataFrame

In [22]:
df.rename({"population":"population" ,"country":"country"} ,axis =1)

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [23]:
df.rename(columns={"country":"Country"})

          Country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [24]:
df.rename({"country":"Country"} ,axis=1 ,inplace = True)
df

          Country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [25]:
df.Country

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: Country, Length: 1704, dtype: object

In [26]:
df.drop('continent',axis=1)

          Country  year  population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [27]:
df.drop(columns=['continent'])

          Country  year  population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [28]:
df.head()

       Country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [29]:
df.drop(columns=['continent'])

          Country  year  population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [30]:
df.drop('continent',axis=1)

          Country  year  population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [31]:
df.head()

       Country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [32]:
df.drop('continent',axis=1)

          Country  year  population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [33]:
df.drop("continent",axis =1,inplace=True)

In [34]:
df.head()

       Country  year  population  life_exp     gdp_cap
0  Afghanistan  1952     8425333    28.801  779.445314
1  Afghanistan  1957     9240934    30.332  820.853030
2  Afghanistan  1962    10267083    31.997  853.100710
3  Afghanistan  1967    11537966    34.020  836.197138
4  Afghanistan  1972    13079460    36.088  739.981106

In [35]:
df["year+7"] = df["year"] +7
df.head()

       Country  year  population  life_exp     gdp_cap  year+7
0  Afghanistan  1952     8425333    28.801  779.445314    1959
1  Afghanistan  1957     9240934    30.332  820.853030    1964
2  Afghanistan  1962    10267083    31.997  853.100710    1969
3  Afghanistan  1967    11537966    34.020  836.197138    1974
4  Afghanistan  1972    13079460    36.088  739.981106    1979

In [36]:
df["gdp"] =df["gdp_cap"]*df["population"]
df.head()

       Country  year  population  life_exp     gdp_cap  year+7           gdp
0  Afghanistan  1952     8425333    28.801  779.445314    1959  6.567086e+09
1  Afghanistan  1957     9240934    30.332  820.853030    1964  7.585449e+09
2  Afghanistan  1962    10267083    31.997  853.100710    1969  8.758856e+09
3  Afghanistan  1967    11537966    34.020  836.197138    1974  9.648014e+09
4  Afghanistan  1972    13079460    36.088  739.981106    1979  9.678553e+09

In [37]:
df["own"]=[i for i in range(1704)]
df

,Country,year,population,life_exp,gdp_cap,year+7,gdp,own
0,Afghanistan,1952,8425333,28.801,779.445314,1959,6.567086e+09,0
1,Afghanistan,1957,9240934,30.332,820.853030,1964,7.585449e+09,1
2,Afghanistan,1962,10267083,31.997,853.100710,1969,8.758856e+09,2
3,Afghanistan,1967,11537966,34.020,836.197138,1974,9.648014e+09,3
4,Afghanistan,1972,13079460,36.088,739.981106,1979,9.678553e+09,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,1987,9216418,62.351,706.157306,1994,6.508241e+09,1699
1700,Zimbabwe,1992,10704340,60.377,693.420786,1999,7.422612e+09,1700
1701,Zimbabwe,1997,11404948,46.809,792.449960,2004,9.037851e+09,1701
1702,Zimbabwe,2002,11926563,39.989,672.038623,2009,8.015111e+09,1702
1703,Zimbabwe,2007,12311143,43.487,469.709298,2014,5.782658e+09,1703

In [38]:
df.drop(columns=["own",'gdp', 'year+7'], axis = 1, inplace = True)
df

          Country  year  population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [39]:
df.index.values

array([   0,    1,    2, ..., 1701, 1702, 1703], shape=(1704,))

In [40]:
df.index = list(range(1, df.shape[0]+1))
df

          Country  year  population  life_exp     gdp_cap
1     Afghanistan  1952     8425333    28.801  779.445314
2     Afghanistan  1957     9240934    30.332  820.853030
3     Afghanistan  1962    10267083    31.997  853.100710
4     Afghanistan  1967    11537966    34.020  836.197138
5     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1700     Zimbabwe  1987     9216418    62.351  706.157306
1701     Zimbabwe  1992    10704340    60.377  693.420786
1702     Zimbabwe  1997    11404948    46.809  792.449960
1703     Zimbabwe  2002    11926563    39.989  672.038623
1704     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [41]:
df.index[1]

np.int64(2)

In [42]:
df.index = np.arange(1, df.shape[0]+1, dtype='float')
df

            Country  year  population  life_exp     gdp_cap
1.0     Afghanistan  1952     8425333    28.801  779.445314
2.0     Afghanistan  1957     9240934    30.332  820.853030
3.0     Afghanistan  1962    10267083    31.997  853.100710
4.0     Afghanistan  1967    11537966    34.020  836.197138
5.0     Afghanistan  1972    13079460    36.088  739.981106
...             ...   ...         ...       ...         ...
1700.0     Zimbabwe  1987     9216418    62.351  706.157306
1701.0     Zimbabwe  1992    10704340    60.377  693.420786
1702.0     Zimbabwe  1997    11404948    46.809  792.449960
1703.0     Zimbabwe  2002    11926563    39.989  672.038623
1704.0     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [43]:

df.head()

         Country  year  population  life_exp     gdp_cap
1.0  Afghanistan  1952     8425333    28.801  779.445314
2.0  Afghanistan  1957     9240934    30.332  820.853030
3.0  Afghanistan  1962    10267083    31.997  853.100710
4.0  Afghanistan  1967    11537966    34.020  836.197138
5.0  Afghanistan  1972    13079460    36.088  739.981106

In [44]:
df.drop(columns=['life_exp', 'year'], axis = 1, inplace = True)
df

            Country  population     gdp_cap
1.0     Afghanistan     8425333  779.445314
2.0     Afghanistan     9240934  820.853030
3.0     Afghanistan    10267083  853.100710
4.0     Afghanistan    11537966  836.197138
5.0     Afghanistan    13079460  739.981106
...             ...         ...         ...
1700.0     Zimbabwe     9216418  706.157306
1701.0     Zimbabwe    10704340  693.420786
1702.0     Zimbabwe    11404948  792.449960
1703.0     Zimbabwe    11926563  672.038623
1704.0     Zimbabwe    12311143  469.709298

[1704 rows x 3 columns]

In [45]:
df = pd.read_csv(r"C:\Users\rrama\OneDrive\Desktop\Python code\groupby_practice_dataset.csv")

In [46]:
df

,order_id,customer_id,customer_city,product_category,order_date,quantity,unit_price,payment_method,total_amount
0,1001,C100,Delhi,Electronics,2024-01-01,1,500,UPI,500
1,1002,C101,Mumbai,Clothing,2024-01-02,2,1200,Credit Card,2400
2,1003,C102,Bangalore,Grocery,2024-01-03,3,300,Debit Card,900
3,1004,C103,Hyderabad,Furniture,2024-01-04,4,800,Cash,3200
4,1005,C104,Chennai,Electronics,2024-01-05,5,500,UPI,2500
...,...,...,...,...,...,...,...,...,...
95,1096,C115,Delhi,Furniture,2024-04-05,1,800,Cash,800
96,1097,C116,Mumbai,Electronics,2024-04-06,2,500,UPI,1000
97,1098,C117,Bangalore,Clothing,2024-04-07,3,1200,Credit Card,3600
98,1099,C118,Hyderabad,Grocery,2024-04-08,4,300,Debit Card,1200
99,1100,C119,Chennai,Furniture,2024-04-09,5,800,Cash,4000

In [47]:
df.groupby(['product_category'])['total_amount'].sum()

product_category
Clothing       90000
Electronics    37500
Furniture      60000
Grocery        22500
Name: total_amount, dtype: int64

In [48]:
df.groupby(['product_category']) ['unit_price'].mean()

product_category
Clothing       1200.0
Electronics     500.0
Furniture       800.0
Grocery         300.0
Name: unit_price, dtype: float64

In [49]:
df.groupby(['customer_city'])['quantity'].sum()

customer_city
Bangalore     60
Chennai      100
Delhi         20
Hyderabad     80
Mumbai        40
Name: quantity, dtype: int64

In [50]:
df.groupby(['payment_method'])['order_id'].count()

payment_method
Cash           25
Credit Card    25
Debit Card     25
UPI            25
Name: order_id, dtype: int64

In [51]:
df.groupby(['customer_city'])['total_amount'].max()

customer_city
Bangalore    3600
Chennai      6000
Delhi        1200
Hyderabad    4800
Mumbai       2400
Name: total_amount, dtype: int64

In [52]:
df.groupby(['customer_city','product_category'])['total_amount'].sum()

customer_city  product_category
Bangalore      Clothing            18000
               Electronics          7500
               Furniture           12000
               Grocery              4500
Chennai        Clothing            30000
               Electronics         12500
               Furniture           20000
               Grocery              7500
Delhi          Clothing             6000
               Electronics          2500
               Furniture            4000
               Grocery              1500
Hyderabad      Clothing            24000
               Electronics         10000
               Furniture           16000
               Grocery              6000
Mumbai         Clothing            12000
               Electronics          5000
               Furniture            8000
               Grocery              3000
Name: total_amount, dtype: int64

In [53]:
df.groupby(['customer_id'])['total_amount'].mean()

customer_id
C100     500.0
C101    2400.0
C102     900.0
C103    3200.0
C104    2500.0
C105    1200.0
C106     600.0
C107    2400.0
C108    2000.0
C109    6000.0
C110     300.0
C111    1600.0
C112    1500.0
C113    4800.0
C114    1500.0
C115     800.0
C116    1000.0
C117    3600.0
C118    1200.0
C119    4000.0
Name: total_amount, dtype: float64

In [54]:
df.groupby(['order_date'])['total_amount'].sum()

order_date
2024-01-01     500
2024-01-02    2400
2024-01-03     900
2024-01-04    3200
2024-01-05    2500
              ...
2024-04-05     800
2024-04-06    1000
2024-04-07    3600
2024-04-08    1200
2024-04-09    4000
Name: total_amount, Length: 100, dtype: int64

In [55]:
df.groupby(['customer_city'])['total_amount'].sum().nlargest(3)

customer_city
Chennai      70000
Hyderabad    56000
Bangalore    42000
Name: total_amount, dtype: int64

In [56]:
df.groupby(['payment_method']).agg(total_sales=('total_amount','sum'),total_orders=('order_id','count'))

                total_sales  total_orders
payment_method
Cash                  60000            25
Credit Card           90000            25
Debit Card            22500            25
UPI                   37500            25

In [57]:
sales=df.groupby(['product_category','customer_city'])['total_amount'].sum().reset_index()

In [58]:
result = sales.loc[
    sales.groupby('product_category')['total_amount'].idxmax()
]

In [59]:
print(sales)

   product_category customer_city  total_amount
0          Clothing     Bangalore         18000
1          Clothing       Chennai         30000
2          Clothing         Delhi          6000
3          Clothing     Hyderabad         24000
4          Clothing        Mumbai         12000
5       Electronics     Bangalore          7500
6       Electronics       Chennai         12500
7       Electronics         Delhi          2500
8       Electronics     Hyderabad         10000
9       Electronics        Mumbai          5000
10        Furniture     Bangalore         12000
11        Furniture       Chennai         20000
12        Furniture         Delhi          4000
13        Furniture     Hyderabad         16000
14        Furniture        Mumbai          8000
15          Grocery     Bangalore          4500
16          Grocery       Chennai          7500
17          Grocery         Delhi          1500
18          Grocery     Hyderabad          6000
19          Grocery        Mumbai          3000

In [60]:
df.groupby(['product_category','customer_city'])['total_amount'].sum() \
  .reset_index() \
  .loc[lambda x: x.groupby('product_category')['total_amount'].idxmax()]

   product_category customer_city  total_amount
1          Clothing       Chennai         30000
6       Electronics       Chennai         12500
11        Furniture       Chennai         20000
16          Grocery       Chennai          7500

In [61]:
df.groupby(['product_category','customer_city'])['total_amount'].max()

product_category  customer_city
Clothing          Bangalore        3600
                  Chennai          6000
                  Delhi            1200
                  Hyderabad        4800
                  Mumbai           2400
Electronics       Bangalore        1500
                  Chennai          2500
                  Delhi             500
                  Hyderabad        2000
                  Mumbai           1000
Furniture         Bangalore        2400
                  Chennai          4000
                  Delhi             800
                  Hyderabad        3200
                  Mumbai           1600
Grocery           Bangalore         900
                  Chennai          1500
                  Delhi             300
                  Hyderabad        1200
                  Mumbai            600
Name: total_amount, dtype: int64

In [62]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\rrama\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\rrama\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [63]:
import pandas as pd
file_path =r"C:\Users\rrama\OneDrive\Desktop\Python code\ACCOUNT_PERF_DATA (1).xlsx"
med_2026=pd.read_excel(file_path,sheet_name='ACCOUNT_PERFORMANCE_DATA')
med_2026

,Account_number,PORTFOLIO,SSN,Phone No.,Place Name,County,City,State,Zip,Region,Account Open Date,Loan_amount,Loan_status,Last_payment_date,Origination_fico_score,Current_fico_score,Current_outstanding
0,38673575,CREDIT CARD,640-29-9264,405-775-9884,Bromide,Johnston,Bromide,OK,74530,South,2018-03-13,40169,Non-Default,2020-11-27,732,779,1606.76
1,38673576,PERSONAL LOAN,375-37-8517,212-786-7533,Reading Center,Schuyler,Reading Center,NY,14876,Northeast,2019-06-23,187055,Non-Default,2021-08-24,877,877,1870.55
2,38673577,PERSONAL LOAN,073-02-5563,385-775-0225,Ibapah,Tooele,Ibapah,UT,84034,West,2019-09-08,129073,Non-Default,2021-04-10,875,881,16779.49
3,38673578,MORTGAGE,106-98-7919,216-984-8974,Wickliffe,Lake,Wickliffe,OH,44092,Midwest,2020-11-20,428500,Non-Default,2021-01-08,708,757,145690.00
4,38673579,CREDIT CARD,753-07-4655,217-307-8597,Forrest,Livingston,Forrest,IL,61741,Midwest,2018-06-20,71859,Non-Default,2021-08-24,714,708,16527.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24999,38698574,CREDIT CARD,112-98-5765,201-857-6904,Wenonah,Gloucester,Wenonah,NJ,8090,Northeast,2021-08-24,71581,Non-Default,2021-05-08,747,776,29348.21
25000,38698575,PERSONAL LOAN,507-57-2035,209-410-5762,West Point,Calaveras,West Point,CA,95255,West,2018-09-01,110458,Default,2021-01-09,862,906,33137.40
25001,38698576,MORTGAGE,094-02-7375,212-698-6318,Syracuse,Onondaga,Syracuse,NY,13225,Northeast,2019-04-18,796430,Default,2021-08-24,651,684,103535.90
25002,38698577,PERSONAL LOAN,467-99-0614,212-525-5734,Woodbury,Nassau,Woodbury,NY,11797,Northeast,2019-08-15,58455,Default,2020-11-28,878,908,22797.45
25003,38698578,MORTGAGE,191-86-1363,229-974-6770,Grovetown,Columbia,Grovetown,GA,30813,South,2020-11-02,107454,Non-Default,2020-11-22,693,743,33310.74

In [64]:
salary=[1000,3000,5000,7000,3000,4000,80000]

In [65]:
salary

[1000, 3000, 5000, 7000, 3000, 4000, 80000]

In [66]:
unique=list(set(salary))

In [67]:
unique.sort(reverse=True)

In [68]:
second_highest=unique[1]
print(second_highest)

7000

In [69]:
med_2026.head(100)

,Account_number,PORTFOLIO,SSN,Phone No.,Place Name,County,City,State,Zip,Region,Account Open Date,Loan_amount,Loan_status,Last_payment_date,Origination_fico_score,Current_fico_score,Current_outstanding
0,38673575,CREDIT CARD,640-29-9264,405-775-9884,Bromide,Johnston,Bromide,OK,74530,South,2018-03-13,40169,Non-Default,2020-11-27,732,779,1606.76
1,38673576,PERSONAL LOAN,375-37-8517,212-786-7533,Reading Center,Schuyler,Reading Center,NY,14876,Northeast,2019-06-23,187055,Non-Default,2021-08-24,877,877,1870.55
2,38673577,PERSONAL LOAN,073-02-5563,385-775-0225,Ibapah,Tooele,Ibapah,UT,84034,West,2019-09-08,129073,Non-Default,2021-04-10,875,881,16779.49
3,38673578,MORTGAGE,106-98-7919,216-984-8974,Wickliffe,Lake,Wickliffe,OH,44092,Midwest,2020-11-20,428500,Non-Default,2021-01-08,708,757,145690.00
4,38673579,CREDIT CARD,753-07-4655,217-307-8597,Forrest,Livingston,Forrest,IL,61741,Midwest,2018-06-20,71859,Non-Default,2021-08-24,714,708,16527.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,38673670,CREDIT CARD,119-98-5733,215-753-6443,Conshohocken,Montgomery,Conshohocken,PA,19428,Northeast,2018-04-12,70450,Default,2021-03-23,864,890,11272.00
96,38673671,CREDIT CARD,510-33-2272,209-685-5524,Klamath,Del Norte,Klamath,CA,95548,West,2020-12-12,62200,Non-Default,2021-08-02,755,751,18660.00
97,38673672,CREDIT CARD,168-86-4252,303-439-4051,Westminster,Adams,Westminster,CO,80036,West,2020-11-14,90548,Default,2021-08-24,828,861,9054.80
98,38673673,CREDIT CARD,730-28-5224,302-854-2835,Yorklyn,New Castle,Yorklyn,DE,19736,South,2019-10-05,52977,Non-Default,2021-06-28,811,843,25428.96
99,38673674,PERSONAL LOAN,381-37-7296,210-580-0080,San Antonio,Bexar,San Antonio,TX,78254,South,2019-03-09,78303,Non-Default,2021-08-24,723,733,33670.29

In [70]:
med_2026.tail(100)

,Account_number,PORTFOLIO,SSN,Phone No.,Place Name,County,City,State,Zip,Region,Account Open Date,Loan_amount,Loan_status,Last_payment_date,Origination_fico_score,Current_fico_score,Current_outstanding
24904,38698479,CREDIT CARD,092-02-0144,803-448-0539,Lando,Chester,Lando,SC,29724,South,2021-07-21,88112,Non-Default,2021-07-12,759,809,27314.72
24905,38698480,MORTGAGE,673-48-6681,314-448-4803,Briar,Ripley,Briar,MO,63931,Midwest,2020-05-15,807924,Non-Default,2021-08-24,813,846,96950.88
24906,38698481,MORTGAGE,127-98-1326,205-604-2328,Hazel Green,Madison,Hazel Green,AL,35750,South,2018-05-21,451853,Non-Default,2021-01-13,900,911,76815.01
24907,38698482,CREDIT CARD,540-83-0348,201-848-6649,Absecon,Atlantic,Absecon,NJ,8205,Northeast,2021-08-24,89164,Default,2021-07-04,794,816,32990.68
24908,38698483,MORTGAGE,069-02-1613,210-994-6664,Arlington,Tarrant,Arlington,TX,76094,South,2020-12-16,295455,Non-Default,2021-04-26,748,784,88636.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24999,38698574,CREDIT CARD,112-98-5765,201-857-6904,Wenonah,Gloucester,Wenonah,NJ,8090,Northeast,2021-08-24,71581,Non-Default,2021-05-08,747,776,29348.21
25000,38698575,PERSONAL LOAN,507-57-2035,209-410-5762,West Point,Calaveras,West Point,CA,95255,West,2018-09-01,110458,Default,2021-01-09,862,906,33137.40
25001,38698576,MORTGAGE,094-02-7375,212-698-6318,Syracuse,Onondaga,Syracuse,NY,13225,Northeast,2019-04-18,796430,Default,2021-08-24,651,684,103535.90
25002,38698577,PERSONAL LOAN,467-99-0614,212-525-5734,Woodbury,Nassau,Woodbury,NY,11797,Northeast,2019-08-15,58455,Default,2020-11-28,878,908,22797.45
25003,38698578,MORTGAGE,191-86-1363,229-974-6770,Grovetown,Columbia,Grovetown,GA,30813,South,2020-11-02,107454,Non-Default,2020-11-22,693,743,33310.74

In [71]:
med_2026[100:]

,Account_number,PORTFOLIO,SSN,Phone No.,Place Name,County,City,State,Zip,Region,Account Open Date,Loan_amount,Loan_status,Last_payment_date,Origination_fico_score,Current_fico_score,Current_outstanding
100,38673675,CREDIT CARD,691-18-0845,239-272-2787,Melbourne,Brevard,Melbourne,FL,32919,South,2019-07-19,32077,Non-Default,2021-02-26,862,911,3207.70
101,38673676,MORTGAGE,180-86-1925,316-607-0666,Woodston,Rooks,Woodston,KS,67675,Midwest,2019-06-14,153025,Non-Default,2021-03-14,893,887,41316.75
102,38673677,CREDIT CARD,141-23-8932,201-633-2534,Trenton,Mercer,Trenton,NJ,8601,Northeast,2018-03-21,83565,Non-Default,2021-05-06,715,710,36768.60
103,38673678,MORTGAGE,108-98-2592,208-538-5228,Pollock,Idaho,Pollock,ID,83547,West,2019-11-28,629157,Non-Default,2021-04-19,751,783,132122.97
104,38673679,CREDIT CARD,111-98-5822,201-944-5009,Vineland,Cumberland,Vineland,NJ,8362,Northeast,2020-05-08,47024,Non-Default,2021-08-24,841,888,7994.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24999,38698574,CREDIT CARD,112-98-5765,201-857-6904,Wenonah,Gloucester,Wenonah,NJ,8090,Northeast,2021-08-24,71581,Non-Default,2021-05-08,747,776,29348.21
25000,38698575,PERSONAL LOAN,507-57-2035,209-410-5762,West Point,Calaveras,West Point,CA,95255,West,2018-09-01,110458,Default,2021-01-09,862,906,33137.40
25001,38698576,MORTGAGE,094-02-7375,212-698-6318,Syracuse,Onondaga,Syracuse,NY,13225,Northeast,2019-04-18,796430,Default,2021-08-24,651,684,103535.90
25002,38698577,PERSONAL LOAN,467-99-0614,212-525-5734,Woodbury,Nassau,Woodbury,NY,11797,Northeast,2019-08-15,58455,Default,2020-11-28,878,908,22797.45
25003,38698578,MORTGAGE,191-86-1363,229-974-6770,Grovetown,Columbia,Grovetown,GA,30813,South,2020-11-02,107454,Non-Default,2020-11-22,693,743,33310.74

In [72]:
med_2026[100:200]

,Account_number,PORTFOLIO,SSN,Phone No.,Place Name,County,City,State,Zip,Region,Account Open Date,Loan_amount,Loan_status,Last_payment_date,Origination_fico_score,Current_fico_score,Current_outstanding
100,38673675,CREDIT CARD,691-18-0845,239-272-2787,Melbourne,Brevard,Melbourne,FL,32919,South,2019-07-19,32077,Non-Default,2021-02-26,862,911,3207.70
101,38673676,MORTGAGE,180-86-1925,316-607-0666,Woodston,Rooks,Woodston,KS,67675,Midwest,2019-06-14,153025,Non-Default,2021-03-14,893,887,41316.75
102,38673677,CREDIT CARD,141-23-8932,201-633-2534,Trenton,Mercer,Trenton,NJ,8601,Northeast,2018-03-21,83565,Non-Default,2021-05-06,715,710,36768.60
103,38673678,MORTGAGE,108-98-2592,208-538-5228,Pollock,Idaho,Pollock,ID,83547,West,2019-11-28,629157,Non-Default,2021-04-19,751,783,132122.97
104,38673679,CREDIT CARD,111-98-5822,201-944-5009,Vineland,Cumberland,Vineland,NJ,8362,Northeast,2020-05-08,47024,Non-Default,2021-08-24,841,888,7994.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,38673770,CREDIT CARD,300-15-9065,479-377-6005,Cabot,Lonoke,Cabot,AR,72023,South,2021-03-01,96731,Non-Default,2021-07-10,857,849,31921.23
196,38673771,MORTGAGE,412-99-8567,215-440-7848,North Bend,Clinton,North Bend,PA,17760,Northeast,2020-04-12,743210,Default,2021-08-24,819,844,81753.10
197,38673772,CREDIT CARD,545-99-7600,406-350-9177,Bozeman,Gallatin,Bozeman,MT,59772,West,2020-06-05,74908,Non-Default,2021-08-12,664,691,23221.48
198,38673773,CREDIT CARD,317-35-5556,202-883-5300,Washington,District of Columbia,Washington,DC,20502,South,2018-09-13,26941,Default,2020-12-31,663,661,538.82
199,38673774,MORTGAGE,172-86-2124,303-723-8684,Eckley,Yuma,Eckley,CO,80727,West,2021-06-27,512711,Non-Default,2021-03-27,732,780,199957.29

# HOW TO CREATE A NEW DATASET FROM AN EXSITING DATASET

In [73]:
med_2026_v1=med_2026
med_2026_v1

,Account_number,PORTFOLIO,SSN,Phone No.,Place Name,County,City,State,Zip,Region,Account Open Date,Loan_amount,Loan_status,Last_payment_date,Origination_fico_score,Current_fico_score,Current_outstanding
0,38673575,CREDIT CARD,640-29-9264,405-775-9884,Bromide,Johnston,Bromide,OK,74530,South,2018-03-13,40169,Non-Default,2020-11-27,732,779,1606.76
1,38673576,PERSONAL LOAN,375-37-8517,212-786-7533,Reading Center,Schuyler,Reading Center,NY,14876,Northeast,2019-06-23,187055,Non-Default,2021-08-24,877,877,1870.55
2,38673577,PERSONAL LOAN,073-02-5563,385-775-0225,Ibapah,Tooele,Ibapah,UT,84034,West,2019-09-08,129073,Non-Default,2021-04-10,875,881,16779.49
3,38673578,MORTGAGE,106-98-7919,216-984-8974,Wickliffe,Lake,Wickliffe,OH,44092,Midwest,2020-11-20,428500,Non-Default,2021-01-08,708,757,145690.00
4,38673579,CREDIT CARD,753-07-4655,217-307-8597,Forrest,Livingston,Forrest,IL,61741,Midwest,2018-06-20,71859,Non-Default,2021-08-24,714,708,16527.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24999,38698574,CREDIT CARD,112-98-5765,201-857-6904,Wenonah,Gloucester,Wenonah,NJ,8090,Northeast,2021-08-24,71581,Non-Default,2021-05-08,747,776,29348.21
25000,38698575,PERSONAL LOAN,507-57-2035,209-410-5762,West Point,Calaveras,West Point,CA,95255,West,2018-09-01,110458,Default,2021-01-09,862,906,33137.40
25001,38698576,MORTGAGE,094-02-7375,212-698-6318,Syracuse,Onondaga,Syracuse,NY,13225,Northeast,2019-04-18,796430,Default,2021-08-24,651,684,103535.90
25002,38698577,PERSONAL LOAN,467-99-0614,212-525-5734,Woodbury,Nassau,Woodbury,NY,11797,Northeast,2019-08-15,58455,Default,2020-11-28,878,908,22797.45
25003,38698578,MORTGAGE,191-86-1363,229-974-6770,Grovetown,Columbia,Grovetown,GA,30813,South,2020-11-02,107454,Non-Default,2020-11-22,693,743,33310.74

In [74]:
med_2026_v1=med_2026.copy()
med_2026_v1

,Account_number,PORTFOLIO,SSN,Phone No.,Place Name,County,City,State,Zip,Region,Account Open Date,Loan_amount,Loan_status,Last_payment_date,Origination_fico_score,Current_fico_score,Current_outstanding
0,38673575,CREDIT CARD,640-29-9264,405-775-9884,Bromide,Johnston,Bromide,OK,74530,South,2018-03-13,40169,Non-Default,2020-11-27,732,779,1606.76
1,38673576,PERSONAL LOAN,375-37-8517,212-786-7533,Reading Center,Schuyler,Reading Center,NY,14876,Northeast,2019-06-23,187055,Non-Default,2021-08-24,877,877,1870.55
2,38673577,PERSONAL LOAN,073-02-5563,385-775-0225,Ibapah,Tooele,Ibapah,UT,84034,West,2019-09-08,129073,Non-Default,2021-04-10,875,881,16779.49
3,38673578,MORTGAGE,106-98-7919,216-984-8974,Wickliffe,Lake,Wickliffe,OH,44092,Midwest,2020-11-20,428500,Non-Default,2021-01-08,708,757,145690.00
4,38673579,CREDIT CARD,753-07-4655,217-307-8597,Forrest,Livingston,Forrest,IL,61741,Midwest,2018-06-20,71859,Non-Default,2021-08-24,714,708,16527.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24999,38698574,CREDIT CARD,112-98-5765,201-857-6904,Wenonah,Gloucester,Wenonah,NJ,8090,Northeast,2021-08-24,71581,Non-Default,2021-05-08,747,776,29348.21
25000,38698575,PERSONAL LOAN,507-57-2035,209-410-5762,West Point,Calaveras,West Point,CA,95255,West,2018-09-01,110458,Default,2021-01-09,862,906,33137.40
25001,38698576,MORTGAGE,094-02-7375,212-698-6318,Syracuse,Onondaga,Syracuse,NY,13225,Northeast,2019-04-18,796430,Default,2021-08-24,651,684,103535.90
25002,38698577,PERSONAL LOAN,467-99-0614,212-525-5734,Woodbury,Nassau,Woodbury,NY,11797,Northeast,2019-08-15,58455,Default,2020-11-28,878,908,22797.45
25003,38698578,MORTGAGE,191-86-1363,229-974-6770,Grovetown,Columbia,Grovetown,GA,30813,South,2020-11-02,107454,Non-Default,2020-11-22,693,743,33310.74

# HOW  TO DESCRIBE  YOU DATASET

In [75]:
med_2026.info
# all set of record in the dataset

<bound method DataFrame.info of        Account_number      PORTFOLIO          SSN    Phone No.   \
0            38673575    CREDIT CARD  640-29-9264  405-775-9884
1            38673576  PERSONAL LOAN  375-37-8517  212-786-7533
2            38673577  PERSONAL LOAN  073-02-5563  385-775-0225
3            38673578       MORTGAGE  106-98-7919  216-984-8974
4            38673579    CREDIT CARD  753-07-4655  217-307-8597
...               ...            ...          ...           ...
24999        38698574    CREDIT CARD  112-98-5765  201-857-6904
25000        38698575  PERSONAL LOAN  507-57-2035  209-410-5762
25001        38698576       MORTGAGE  094-02-7375  212-698-6318
25002        38698577  PERSONAL LOAN  467-99-0614  212-525-5734
25003        38698578       MORTGAGE  191-86-1363  229-974-6770

           Place Name      County            City State    Zip     Region  \
0             Bromide    Johnston         Bromide    OK  74530      South
1      Reading Center    Schuyler  Reading Center    NY  14876  Northeast
2              Ibapah      Tooele          Ibapah    UT  84034       West
3           Wickliffe        Lake       Wickliffe    OH  44092    Midwest
4             Forrest  Livingston         Forrest    IL  61741    Midwest
...               ...         ...             ...   ...    ...        ...
24999         Wenonah  Gloucester         Wenonah    NJ   8090  Northeast
25000      West Point   Calaveras      West Point    CA  95255       West
25001        Syracuse    Onondaga        Syracuse    NY  13225  Northeast
25002        Woodbury      Nassau        Woodbury    NY  11797  Northeast
25003       Grovetown    Columbia       Grovetown    GA  30813      South

      Account Open Date  Loan_amount  Loan_status Last_payment_date  \
0            2018-03-13        40169  Non-Default        2020-11-27
1            2019-06-23       187055  Non-Default        2021-08-24
2            2019-09-08       129073  Non-Default        2021-04-10
3            2020-11-20       428500  Non-Default        2021-01-08
4            2018-06-20        71859  Non-Default        2021-08-24
...                 ...          ...          ...               ...
24999        2021-08-24        71581  Non-Default        2021-05-08
25000        2018-09-01       110458      Default        2021-01-09
25001        2019-04-18       796430      Default        2021-08-24
25002        2019-08-15        58455      Default        2020-11-28
25003        2020-11-02       107454  Non-Default        2020-11-22

       Origination_fico_score  Current_fico_score  Current_outstanding
0                         732                 779              1606.76
1                         877                 877              1870.55
2                         875                 881             16779.49
3                         708                 757            145690.00
4                         714                 708             16527.57
...                       ...                 ...                  ...
24999                     747                 776             29348.21
25000                     862                 906             33137.40
25001                     651                 684            103535.90
25002                     878                 908             22797.45
25003                     693                 743             33310.74

[25004 rows x 17 columns]>

In [76]:
med_2026.columns.values
# lists of header in the dataset

array(['Account_number', 'PORTFOLIO', 'SSN', 'Phone No. ', 'Place Name',
       'County', 'City', 'State', 'Zip', 'Region', 'Account Open Date',
       'Loan_amount', 'Loan_status', 'Last_payment_date',
       'Origination_fico_score', 'Current_fico_score',
       'Current_outstanding'], dtype=object)

In [77]:
med_2026.count()
# count of record in  each variable

Account_number            25004
PORTFOLIO                 25004
SSN                       25004
Phone No.                 24879
Place Name                25004
County                    25004
City                      24993
State                     25004
Zip                       25004
Region                    25004
Account Open Date         25004
Loan_amount               25004
Loan_status               24998
Last_payment_date         25004
Origination_fico_score    25004
Current_fico_score        25004
Current_outstanding       24990
dtype: int64

In [78]:
med_2026.describe()
# give you the statistics for all numeric variables

,Account_number,Zip,Account Open Date,Loan_amount,Last_payment_date,Origination_fico_score,Current_fico_score,Current_outstanding
count,2.500400e+04,25004.000000,25004,25004.000000,25004,25004.000000,25004.000000,24990.000000
mean,3.868608e+07,49457.084027,2019-12-22 19:25:48.616221440,263299.361942,2021-05-09 04:19:54.432890624,774.140178,794.258959,66204.627569
min,3.867358e+07,215.000000,2018-01-01 00:00:00,25006.000000,2020-10-28 00:00:00,650.000000,640.000000,0.000000
25%,3.867983e+07,26054.500000,2018-12-25 00:00:00,63198.000000,2021-02-11 00:00:00,712.000000,731.000000,11499.880000
50%,3.868608e+07,48603.500000,2019-12-26 00:00:00,106356.000000,2021-05-27 00:00:00,774.000000,794.000000,26440.890000
75%,3.869233e+07,72705.250000,2021-01-01 00:00:00,421972.250000,2021-08-24 00:00:00,837.000000,857.000000,76241.820000
max,3.869858e+07,99950.000000,2021-08-24 00:00:00,999838.000000,2021-08-24 00:00:00,900.000000,949.000000,498731.500000
std,7.218177e+03,27778.686162,NaN,283185.047200,NaN,72.419555,74.537289,91332.699779

In [79]:
med_2026.info()
# it will give the variables data types and count of records in each

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25004 entries, 0 to 25003
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Account_number          25004 non-null  int64
 1   PORTFOLIO               25004 non-null  object
 2   SSN                     25004 non-null  object
 3   Phone No.               24879 non-null  object
 4   Place Name              25004 non-null  object
 5   County                  25004 non-null  object
 6   City                    24993 non-null  object
 7   State                   25004 non-null  object
 8   Zip                     25004 non-null  int64
 9   Region                  25004 non-null  object
 10  Account Open Date       25004 non-null  datetime64[ns]
 11  Loan_amount             25004 non-null  int64
 12  Loan_status             24998 non-null  object
 13  Last_payment_date       25004 non-null  datetime64[ns]
 14  Origination_fico_score  25004 non-null  int64
 15  Current_fico_score      25004 non-null  int64
 16  Current_outstanding     24990 non-null  float64
dtypes: datetime64[ns](2), float64(1), int64(5), object(9)
memory usage: 3.2+ MB

In [80]:
med_2026.isnull().sum()
# it gives each variables wise count  of missing values

Account_number              0
PORTFOLIO                   0
SSN                         0
Phone No.                 125
Place Name                  0
County                      0
City                       11
State                       0
Zip                         0
Region                      0
Account Open Date           0
Loan_amount                 0
Loan_status                 6
Last_payment_date           0
Origination_fico_score      0
Current_fico_score          0
Current_outstanding        14
dtype: int64

In [81]:
med_2026.isnull().sum().sum()
# this gives each overall missing counts in the dataset

np.int64(156)

HOW TO CREATE  A NEW DATASET FROM AN EXSTING DATASET BY SELECTING VARIABLES AND DROPPING VARIABLES

In [82]:
med_2026.columns.values

array(['Account_number', 'PORTFOLIO', 'SSN', 'Phone No. ', 'Place Name',
       'County', 'City', 'State', 'Zip', 'Region', 'Account Open Date',
       'Loan_amount', 'Loan_status', 'Last_payment_date',
       'Origination_fico_score', 'Current_fico_score',
       'Current_outstanding'], dtype=object)

In [83]:
med_2026_v1=med_2026[['Account_number','PORTFOLIO','SSN','County','State']]

In [84]:
med_2026_v1

       Account_number      PORTFOLIO          SSN      County State
0            38673575    CREDIT CARD  640-29-9264    Johnston    OK
1            38673576  PERSONAL LOAN  375-37-8517    Schuyler    NY
2            38673577  PERSONAL LOAN  073-02-5563      Tooele    UT
3            38673578       MORTGAGE  106-98-7919        Lake    OH
4            38673579    CREDIT CARD  753-07-4655  Livingston    IL
...               ...            ...          ...         ...   ...
24999        38698574    CREDIT CARD  112-98-5765  Gloucester    NJ
25000        38698575  PERSONAL LOAN  507-57-2035   Calaveras    CA
25001        38698576       MORTGAGE  094-02-7375    Onondaga    NY
25002        38698577  PERSONAL LOAN  467-99-0614      Nassau    NY
25003        38698578       MORTGAGE  191-86-1363    Columbia    GA

[25004 rows x 5 columns]

In [85]:
list_vars=['Account_number','PORTFOLIO','SSN','County','State']
med_2026_v2=med_2026[list_vars]
med_2026_v2

       Account_number      PORTFOLIO          SSN      County State
0            38673575    CREDIT CARD  640-29-9264    Johnston    OK
1            38673576  PERSONAL LOAN  375-37-8517    Schuyler    NY
2            38673577  PERSONAL LOAN  073-02-5563      Tooele    UT
3            38673578       MORTGAGE  106-98-7919        Lake    OH
4            38673579    CREDIT CARD  753-07-4655  Livingston    IL
...               ...            ...          ...         ...   ...
24999        38698574    CREDIT CARD  112-98-5765  Gloucester    NJ
25000        38698575  PERSONAL LOAN  507-57-2035   Calaveras    CA
25001        38698576       MORTGAGE  094-02-7375    Onondaga    NY
25002        38698577  PERSONAL LOAN  467-99-0614      Nassau    NY
25003        38698578       MORTGAGE  191-86-1363    Columbia    GA

[25004 rows x 5 columns]

In [86]:
# how to create a new dataset by selecting number of observations
list_vars=['Account_number','PORTFOLIO','SSN','County','State']
med_2026_v3=med_2026[list_vars][0:100]
med_2026_v3

    Account_number      PORTFOLIO          SSN      County State
0         38673575    CREDIT CARD  640-29-9264    Johnston    OK
1         38673576  PERSONAL LOAN  375-37-8517    Schuyler    NY
2         38673577  PERSONAL LOAN  073-02-5563      Tooele    UT
3         38673578       MORTGAGE  106-98-7919        Lake    OH
4         38673579    CREDIT CARD  753-07-4655  Livingston    IL
..             ...            ...          ...         ...   ...
95        38673670    CREDIT CARD  119-98-5733  Montgomery    PA
96        38673671    CREDIT CARD  510-33-2272   Del Norte    CA
97        38673672    CREDIT CARD  168-86-4252       Adams    CO
98        38673673    CREDIT CARD  730-28-5224  New Castle    DE
99        38673674  PERSONAL LOAN  381-37-7296       Bexar    TX

[100 rows x 5 columns]

In [87]:
# how  to create a new dataset by dropping variables
med_2026.columns.values

array(['Account_number', 'PORTFOLIO', 'SSN', 'Phone No. ', 'Place Name',
       'County', 'City', 'State', 'Zip', 'Region', 'Account Open Date',
       'Loan_amount', 'Loan_status', 'Last_payment_date',
       'Origination_fico_score', 'Current_fico_score',
       'Current_outstanding'], dtype=object)

In [88]:
med_2026_v4=med_2026.drop(['City','Zip','Last_payment_date','Origination_fico_score', 'Current_fico_score','Current_outstanding'],axis=1)
med_2026_v4

,Account_number,PORTFOLIO,SSN,Phone No.,Place Name,County,State,Region,Account Open Date,Loan_amount,Loan_status
0,38673575,CREDIT CARD,640-29-9264,405-775-9884,Bromide,Johnston,OK,South,2018-03-13,40169,Non-Default
1,38673576,PERSONAL LOAN,375-37-8517,212-786-7533,Reading Center,Schuyler,NY,Northeast,2019-06-23,187055,Non-Default
2,38673577,PERSONAL LOAN,073-02-5563,385-775-0225,Ibapah,Tooele,UT,West,2019-09-08,129073,Non-Default
3,38673578,MORTGAGE,106-98-7919,216-984-8974,Wickliffe,Lake,OH,Midwest,2020-11-20,428500,Non-Default
4,38673579,CREDIT CARD,753-07-4655,217-307-8597,Forrest,Livingston,IL,Midwest,2018-06-20,71859,Non-Default
...,...,...,...,...,...,...,...,...,...,...,...
24999,38698574,CREDIT CARD,112-98-5765,201-857-6904,Wenonah,Gloucester,NJ,Northeast,2021-08-24,71581,Non-Default
25000,38698575,PERSONAL LOAN,507-57-2035,209-410-5762,West Point,Calaveras,CA,West,2018-09-01,110458,Default
25001,38698576,MORTGAGE,094-02-7375,212-698-6318,Syracuse,Onondaga,NY,Northeast,2019-04-18,796430,Default
25002,38698577,PERSONAL LOAN,467-99-0614,212-525-5734,Woodbury,Nassau,NY,Northeast,2019-08-15,58455,Default
25003,38698578,MORTGAGE,191-86-1363,229-974-6770,Grovetown,Columbia,GA,South,2020-11-02,107454,Non-Default

In [89]:
med_2026_v4.columns.value_counts()

Account_number       1
PORTFOLIO            1
SSN                  1
Phone No.            1
Place Name           1
County               1
State                1
Region               1
Account Open Date    1
Loan_amount          1
Loan_status          1
Name: count, dtype: int64

In [90]:
med_2026_v4.columns.size

11

In [91]:
drop_list_values=['City','Zip','Last_payment_date','Origination_fico_score', 'Current_fico_score','Current_outstanding']
med_2026_v4=med_2026.drop(drop_list_values,axis=1)
med_2026_v4

,Account_number,PORTFOLIO,SSN,Phone No.,Place Name,County,State,Region,Account Open Date,Loan_amount,Loan_status
0,38673575,CREDIT CARD,640-29-9264,405-775-9884,Bromide,Johnston,OK,South,2018-03-13,40169,Non-Default
1,38673576,PERSONAL LOAN,375-37-8517,212-786-7533,Reading Center,Schuyler,NY,Northeast,2019-06-23,187055,Non-Default
2,38673577,PERSONAL LOAN,073-02-5563,385-775-0225,Ibapah,Tooele,UT,West,2019-09-08,129073,Non-Default
3,38673578,MORTGAGE,106-98-7919,216-984-8974,Wickliffe,Lake,OH,Midwest,2020-11-20,428500,Non-Default
4,38673579,CREDIT CARD,753-07-4655,217-307-8597,Forrest,Livingston,IL,Midwest,2018-06-20,71859,Non-Default
...,...,...,...,...,...,...,...,...,...,...,...
24999,38698574,CREDIT CARD,112-98-5765,201-857-6904,Wenonah,Gloucester,NJ,Northeast,2021-08-24,71581,Non-Default
25000,38698575,PERSONAL LOAN,507-57-2035,209-410-5762,West Point,Calaveras,CA,West,2018-09-01,110458,Default
25001,38698576,MORTGAGE,094-02-7375,212-698-6318,Syracuse,Onondaga,NY,Northeast,2019-04-18,796430,Default
25002,38698577,PERSONAL LOAN,467-99-0614,212-525-5734,Woodbury,Nassau,NY,Northeast,2019-08-15,58455,Default
25003,38698578,MORTGAGE,191-86-1363,229-974-6770,Grovetown,Columbia,GA,South,2020-11-02,107454,Non-Default

# HOW TO RETRIVE DATA BY GIVEN CRITERIAS FOR FILTERING

In [92]:
# WE CAN FILTER DATA USING OPERATORS AND OPERANDS

# THERE ARE 4 TYPES OF OPERATORS
# LOGICAL OPERATOR (AND,OR,IN,NOT,IN)
# COMPARISON OPERATOR (=,>,<,>=,<=,<>)
# SPECIAL OPERATOR(LIKE,BETWEEN,AND)
# ARITHEMATIC OPERATOR(+,-,/,//,%)

In [93]:
# THERE ARE 4 TYPES OF OPERATORS
list_vars=['Account_number','PORTFOLIO','SSN','County','State']
med_2026_v5=med_2026[list_vars][med_2026['PORTFOLIO']=='PERSONAL LOAN']
med_2026_v5

       Account_number      PORTFOLIO          SSN     County State
1            38673576  PERSONAL LOAN  375-37-8517   Schuyler    NY
2            38673577  PERSONAL LOAN  073-02-5563     Tooele    UT
7            38673582  PERSONAL LOAN  390-33-0765      Anoka    MN
15           38673590  PERSONAL LOAN  233-57-1697       Rush    IN
16           38673591  PERSONAL LOAN  668-48-6539     Cooper    MO
...               ...            ...          ...        ...   ...
24981        38698556  PERSONAL LOAN  492-29-1690   Randolph    WV
24992        38698567  PERSONAL LOAN  016-94-9378   Saguache    CO
24994        38698569  PERSONAL LOAN  596-94-1180  Riverside    CA
25000        38698575  PERSONAL LOAN  507-57-2035  Calaveras    CA
25002        38698577  PERSONAL LOAN  467-99-0614     Nassau    NY

[5036 rows x 5 columns]

In [94]:
list_vars=['Account_number','PORTFOLIO','SSN','County','State']
med_2026_v5=med_2026[list_vars][(med_2026['PORTFOLIO']=='PERSONAL LOAN') & (med_2026['County']=='Cooper')]
med_2026_v5

       Account_number      PORTFOLIO          SSN  County State
16           38673591  PERSONAL LOAN  668-48-6539  Cooper    MO
18075        38691650  PERSONAL LOAN  428-99-4067  Cooper    MO
23800        38697375  PERSONAL LOAN  544-81-9960  Cooper    MO

In [95]:
list_vars=['Account_number','PORTFOLIO','SSN','County','State']
med_2026_v5=med_2026[list_vars][med_2026['PORTFOLIO']!='PERSONAL LOAN']
med_2026_v5

       Account_number    PORTFOLIO          SSN      County State
0            38673575  CREDIT CARD  640-29-9264    Johnston    OK
3            38673578     MORTGAGE  106-98-7919        Lake    OH
4            38673579  CREDIT CARD  753-07-4655  Livingston    IL
5            38673580     MORTGAGE  770-02-0049      Sussex    NJ
6            38673581  CREDIT CARD  090-02-6498   Middlesex    MA
...               ...          ...          ...         ...   ...
24997        38698572     MORTGAGE  725-18-5262     Volusia    FL
24998        38698573     MORTGAGE  500-29-4129  Mille Lacs    MN
24999        38698574  CREDIT CARD  112-98-5765  Gloucester    NJ
25001        38698576     MORTGAGE  094-02-7375    Onondaga    NY
25003        38698578     MORTGAGE  191-86-1363    Columbia    GA

[19968 rows x 5 columns]

In [96]:
list_vars=['Account_number','PORTFOLIO','SSN','County','State']
med_2026_v5=med_2026[list_vars][med_2026['PORTFOLIO'] .isin (['PERSONAL LOAN','CREDIT CARD','MORTGAGE'])]
med_2026_v5

       Account_number      PORTFOLIO          SSN      County State
0            38673575    CREDIT CARD  640-29-9264    Johnston    OK
1            38673576  PERSONAL LOAN  375-37-8517    Schuyler    NY
2            38673577  PERSONAL LOAN  073-02-5563      Tooele    UT
3            38673578       MORTGAGE  106-98-7919        Lake    OH
4            38673579    CREDIT CARD  753-07-4655  Livingston    IL
...               ...            ...          ...         ...   ...
24999        38698574    CREDIT CARD  112-98-5765  Gloucester    NJ
25000        38698575  PERSONAL LOAN  507-57-2035   Calaveras    CA
25001        38698576       MORTGAGE  094-02-7375    Onondaga    NY
25002        38698577  PERSONAL LOAN  467-99-0614      Nassau    NY
25003        38698578       MORTGAGE  191-86-1363    Columbia    GA

[25004 rows x 5 columns]

In [97]:
exclude = ['PERSONAL LOAN', 'CREDIT CARD']

filtered_df = med_2026.loc[
    ~med_2026['PORTFOLIO'].isin(exclude)
]

filtered_df

,Account_number,PORTFOLIO,SSN,Phone No.,Place Name,County,City,State,Zip,Region,Account Open Date,Loan_amount,Loan_status,Last_payment_date,Origination_fico_score,Current_fico_score,Current_outstanding
3,38673578,MORTGAGE,106-98-7919,216-984-8974,Wickliffe,Lake,Wickliffe,OH,44092,Midwest,2020-11-20,428500,Non-Default,2021-01-08,708,757,145690.00
5,38673580,MORTGAGE,770-02-0049,201-312-1614,Highland Lakes,Sussex,Highland Lakes,NJ,7422,Northeast,2020-06-26,561395,Non-Default,2021-08-24,812,861,134734.80
9,38673584,MORTGAGE,677-22-7228,307-872-6444,Casper,Natrona,Casper,WY,82601,West,2018-10-20,584738,Non-Default,2021-08-24,878,911,175421.40
10,38673585,MORTGAGE,149-23-6087,479-493-2345,Van Buren,Crawford,Van Buren,AR,72957,South,2019-01-19,469197,Default,2020-11-10,702,722,145451.07
11,38673586,MORTGAGE,211-84-1802,319-658-2317,Moville,Woodbury,Moville,IA,51039,Midwest,2021-08-24,619386,Default,2021-08-09,810,853,284917.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24996,38698571,MORTGAGE,482-41-8559,215-432-2028,Warren,Warren,Warren,PA,16367,Northeast,2019-09-21,229963,Non-Default,2021-08-24,731,721,112681.87
24997,38698572,MORTGAGE,725-18-5262,239-778-5164,Deland,Volusia,Deland,FL,32721,South,2021-07-13,843078,Default,2020-12-10,871,899,421539.00
24998,38698573,MORTGAGE,500-29-4129,218-634-3018,Foreston,Mille Lacs,Foreston,MN,56330,Midwest,2021-08-24,187422,Default,2021-08-24,775,814,80591.46
25001,38698576,MORTGAGE,094-02-7375,212-698-6318,Syracuse,Onondaga,Syracuse,NY,13225,Northeast,2019-04-18,796430,Default,2021-08-24,651,684,103535.90
25003,38698578,MORTGAGE,191-86-1363,229-974-6770,Grovetown,Columbia,Grovetown,GA,30813,South,2020-11-02,107454,Non-Default,2020-11-22,693,743,33310.74

In [98]:
print(cid)

NameError: name 'cid' is not defined

In [ ]:
filtered_df['PORTFOLIO'].value_counts()

In [ ]:
med_2026

In [ ]:
med_2026['PORTFOLIO'].value_counts

In [ ]:
list_vars=['Account_number','PORTFOLIO','SSN','County','State','Zip']	
med_2026_v5=med_2026[list_vars][(med_2026['PORTFOLIO']=='PERSONAL LOAN') | (med_2026['County']=='Cooper')]
med_2026_v5

In [ ]:
# COMPARISON OPERATOR (=,>,<,>=,<=,<>)

list_vars=['Account_number','PORTFOLIO','SSN','County','State','Zip']	
med_2026_v5=med_2026[list_vars][med_2026['Zip']>=50000]
med_2026_v5

In [ ]:
# SPECIAL OPERATOR(LIKE,BETWEEN,AND)

list_vars=['Account_number','PORTFOLIO','SSN','County','State','Zip']	
med_2026_v5=med_2026[list_vars][med_2026['County'].str.startswith('L',na=False)]
med_2026_v5

In [ ]:
list_vars=['Account_number','PORTFOLIO','SSN','County','State','Zip']	
med_2026_v5=med_2026[list_vars][med_2026['County'].str.endswith('e',na=False)]
med_2026_v5

In [ ]:
list_vars=['Account_number','PORTFOLIO','SSN','County','State','Zip']	
med_2026_v5=med_2026[list_vars][med_2026['County'].str.contains('e',na=False)]
med_2026_v5

In [ ]:
list_vars=['Account_number','PORTFOLIO','SSN','County','State','Zip']	
age_fliter=med_2026['Zip'].between(7000,30000,inclusive='both')
med_2026_v5=med_2026[list_vars][age_fliter]
med_2026

In [ ]:
list_vars=['Account_number','PORTFOLIO','SSN','County','State','Zip','Origination_fico_score','Current_fico_score']	
med_2026_v5=med_2026[list_vars]
med_2026_v5['new_column']=med_2026_v5['Current_fico_score'] / med_2026_v5['Origination_fico_score']
med_2026_v5

In [ ]:
list_vars=['Account_number','PORTFOLIO','SSN','County','State','Zip','Origination_fico_score','Current_fico_score']	
med_2026_v5=med_2026[list_vars]
med_2026_v5['new_column']=(med_2026_v5['Current_fico_score'] / med_2026_v5['Origination_fico_score']).apply(lambda x: f"${x:,.2f}")
med_2026_v5

In [ ]:
list_vars=['Account_number','PORTFOLIO','SSN','County','State','Zip','Origination_fico_score','Current_fico_score']	
med_2026_v5=med_2026[list_vars]
med_2026_v5['new_column']=(med_2026_v5['Current_fico_score'] / med_2026_v5['Origination_fico_score']).apply(lambda x: f"${x:,.1f}")
med_2026_v5

In [ ]:
list_vars=['Account_number','PORTFOLIO','SSN','County','State','Zip','Origination_fico_score','Current_fico_score']	
med_2026_v5=med_2026[list_vars]
med_2026_v5['new_column']=(med_2026_v5['Current_fico_score'] / med_2026_v5['Origination_fico_score']).apply(lambda x: f"${x:,.0f}")
med_2026_v5

SORTING DATASET BY VARIABLES

In [ ]:
import pandas as pd
file_name=r"C:\Users\rrama\OneDrive\Desktop\Python code\student_marks_from_image.xlsx"
stu_score=pd.read_excel(file_path)
stu_score

In [ ]:
# lets sort the dataset by stu_name
stu_score_v1=stu_score.sort_values(by=['STU_NAME'])
stu_score

In [ ]:
stu_score_v1=stu_score.sort_values(by=['STU_NAME','SUBJECT','MARKS'])
stu_score

In [ ]:
stu_score_v1=stu_score.sort_values(by=['STU_NAME','YEAR','MARKS'],ascending=[True,True,False])
stu_score_v1

In [ ]:
stu_score_v1.to_excel(r'C:\Users\rrama\OneDrive\Desktop\Python code\stu_score_v1.xlsx',index=False)

In [ ]:
stu_score_v1=stu_score.sort_values(by=['SUBJECT','YEAR','MARKS'],ascending=[True,True,False])
stu_score_v1

# Summarizing Data

In [ ]:
med_2026.info()

In [ ]:
med_2026.count()

In [ ]:
med_2026['Account_number'].count()

In [ ]:
med_2026.groupby('PORTFOLIO')['Account_number'].count()

In [ ]:
med_2026.groupby('PORTFOLIO')['Account_number'].max()

In [ ]:
med_2026.groupby('PORTFOLIO')['Account_number'].min()

In [ ]:
# how to summarize data using more than one categorical field
med_summary=med_2026['Origination_fico_score'].groupby([med_2026['County'],med_2026['City']]).sum()
med_summary

In [ ]:
med_summary=med_2026['Origination_fico_score'].groupby([med_2026['County'],med_2026['City']]).count()
med_summary

In [ ]:
med_summary=med_2026.groupby(['PORTFOLIO'],as_index=False).agg({'Zip':'count','Origination_fico_score':'sum','Current_fico_score':'mean'})
med_summary=med_summary.rename(columns={'Zip':'count_Zip','Origination_fico_score':'Sum_Origination_fico_score','Current_fico_score':'mean_Current_fico_score'})
med_summary

USE OF ELSE IF CONDITION

In [ ]:
list_vars=['Account_number','PORTFOLIO','SSN','County','State','Zip']	
med_2026_v5=med_2026[list_vars]
med_2026_v5=med_2026_v5.rename(columns={'Zip':'Zip_no'})
med_2026_v5

In [ ]:
import numpy as np

In [ ]:
# if then with one condition variable
import pandas as pd
import numpy as np
med_2026_v5['New_Zip']=np.where(med_2026_v5['Zip_no']>60000,'primier','non primier')
med_2026_v5

In [ ]:
med_2026_v5['Discount']=[i*.20 if i<5000 else i*.10 if i < 9000 else i*.05 for i in med_2026_v5.Zip_no]
med_2026_v5

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv(r"C:\Users\rrama\OneDrive\Desktop\Python code\pandas_practice_dataset.csv")
df

In [ ]:
# Display first 10 rows of the dataset.
df.head(10)

In [ ]:
# Display last 5 rows.
df.tail(5)

In [ ]:
# Show column names of the dataset.
df.columns.values

In [ ]:
# Check data types of each column.
df.info()

In [ ]:
# Find total number of missing values per column.
df.isnull().sum()

In [ ]:
# Select only the column sales.
df [["sales"]]

In [ ]:
# Select columns customer_id and region.
df [["customer_id","region"]]

In [ ]:
type(df)

In [ ]:
# Filter rows where sales > 500.
df[df['sales'] > 500]

In [ ]:
# Add a new column profit = revenue - cost.
df['profit']=df['revenue']-df['cost']
df

In [ ]:
# Rename column cust_id to customer_id.
df.rename(columns={'customer_id':'cust_id'})

In [ ]:
# Drop column order_id.
df.drop('order_id',axis=1)

In [ ]:
# Sort dataset by sales descending.
df.sort_values(by='sales',ascending=False)

In [ ]:
# Count number of non-null values in column sales.
len(df['sales'])        # total rows
df['sales'].count()     # non-null only

In [ ]:
# Find unique values in column region.
df['region'].unique()

In [ ]:
# Convert column order_date to datetime.
df.rename(columns={'order_date':'datetime'})

In [ ]:
# Find mean sales by each region.
df.groupby('region')['sales'].mean()
df

In [ ]:
# Find total revenue by product_category.
df.groupby('product_category')['revenue'].sum()

In [ ]:
# Find number of orders per customer.
df.groupby('customer_id')['order_id'].count()

In [ ]:
# Find rows where region is either "East" or "West".
df[df['region'].isin(['East','West'])]

In [ ]:
df.columns

In [ ]:
# Fill missing values in discount column with 0.
df['discount'] = df['discount'].fillna(0)
df

In [ ]:
# Drop rows containing any null values.
df.dropna(how='all')

In [ ]:
# Create a new column sales_tax = 10% of sales.
df['sales_tax']=df['sales']*0.10
df

In [ ]:
# Sort by region ascending and sales descending.
df.sort_values(['region','sales'],ascending=[True,False])

In [ ]:
# Reset DataFrame index.
df.reset_index()

In [ ]:
# Set order_id as index.
df.set_index('order_id')

In [ ]:
# Get top 5 rows with highest sales.
df.nlargest(5, 'sales')

In [ ]:
df.sort_values('sales', ascending=False).head(5)

In [ ]:
# Create a pivot table showing total sales by region and category.
pd.pivot_table(
    df,
    values='sales',
    index='region',
    columns='product_category',
    aggfunc='sum'
)

In [ ]:
# duplicate rows in dataset Find .
df.duplicated()

In [ ]:
# Remove duplicate rows.
df.drop_duplicates()

In [ ]:
# Merge df_orders and df_customers on customer_id.
import pandas as pd

merged_df = pd.merge(df1, df2,on='customer_id')
merged_df

In [ ]:
# Concatenate two DataFrames vertically.
import pandas as pd

result = pd.concat([df1, df2])
result

In [ ]:
# Create a new column year extracted from order_date.
df['year']=df['order_date'].dt.year

In [ ]:
df['order_date'] = pd.to_datetime(df['order_date']).dt.year
df

In [ ]:
# Calculate cumulative sales by date.
df['date']=pd.to_datetime(df['order_date']).dt.date
df=df.sort_values('date')
df['cumulative_sales']=df['sales'].cumsum()
df

In [ ]:
# Find correlation between sales and profit.
df[['sales', 'profit']].corr()

In [ ]:
# Find covariance between numeric columns.
df[['sales', 'profit']].cov()

In [ ]:
# Get row that contains maximum sales.
df.sort_values('sales', ascending=False).head(1)  #slower

In [ ]:
df.loc[df['sales'].idxmax()]    # faster

In [ ]:
# Get row that contains minimum profit.
df.sort_values('profit',ascending=True).head(1)

In [ ]:
df.loc[df['profit'].idxmin()]

In [ ]:
# Apply lambda function to label sales as "High" if >1000 else "Low".
df['sales_label'] = df['sales'].apply(
    lambda x: 'High' if x > 1000 else 'Low'
)
df

In [ ]:
# Calculate rolling 7-day average of sales.
df['date'] = pd.to_datetime(df['date'])
df = df.sort_values('date')
df['rolling_7day_avg_sales'] = df['sales'].rolling(window=7).mean()
df

In [ ]:
# Create bar chart of total sales by region.
import pandas as pd
import matplotlib.pyplot as plt

# Sample example data (replace with your actual DataFrame)
df = pd.DataFrame({
    'region': ['East', 'West', 'East', 'North', 'West', 'North'],
    'sales': [500, 700, 300, 400, 600, 800]
})

# Calculate total sales by region
region_sales = df.groupby('region')['sales'].sum()

# Create bar chart
plt.figure()
plt.bar(region_sales.index, region_sales.values)
plt.xlabel('Region')
plt.ylabel('Total Sales')
plt.title('Total Sales by Region')
plt.show()

In [ ]:
!pip install matplotlib

In [ ]:
# Create bar chart of total sales by region.
df=pd.read_csv(r"C:\Users\rrama\OneDrive\Desktop\Python code\pandas_practice_dataset.csv")
region_sales = df.groupby('region')['sales'].sum()
plt.figure()
plt.bar(region_sales.index, region_sales.values)
plt.xlabel('Region')
plt.ylabel('Total Sales')
plt.title('Total Sales by Region')
plt.show()

In [ ]:
# Randomly sample 10 rows.
df.sample(10)

In [ ]:
df.head(45)

In [ ]:
df

In [ ]:
df['country'].unique()

In [ ]:
df['country'].value_counts()

In [ ]:
df.rename({'population':'Population','country':'Country'},axis=1)

In [ ]:
df.rename(columns={'continent':'Continent'})

In [ ]:
df.rename({'country':'Country'},axis=1,inplace=True)
df

In [1]:
# 1. What is a variable in Python? Give one example.
# A variable is a name used to store a value in memory.
age = 56
print(age)

56

In [ ]:
# 2. Write the syntax to take input from the user in Python.
name = input('Enter your a name')
print(name)
num = int(input('Enter your a num'))
print(num)

In [ ]:
# 3. Differentiate between int and float data types with examples.
# int - Stores whole number. ex-10
# flote - stores desimal number. ex-29.4

In [1]:
# 4. What will be the output of the following code?
print(type("25"))

<class 'str'>

In [3]:
# 5. Write a program to swap two numbers using a temporary variable.
a = 5
b = 10
temp = a
a = b 
b = temp
print('a=',a )
print('b=',b )

a= 10
b= 5

In [4]:
# 6. What is the difference between = and == in Python?
# = Assignment operator(Assign values)    == Comparision operator.(cheak quality)

In [5]:
# 7. Write a Python statement to print "Hello World".
print('Hello World')

Hello World

In [7]:
# 8. Name any four built-in data types in Python.
# int
# float
# str
# list

In [8]:
# 9. What is indentation in Python and why is it important?
# indentation means gives spaces at the beginning of a line.It is important because Python uses indentation to define blocks of code.

In [9]:
# 10. Write a Python expression to find the remainder when 17 is divided by 5.
print(17 % 5)

2