In [2]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Users\rrama\OneDrive\Desktop\Python code\ecommerce_orders_dataset.csv")
df

,order_id,order_date,customer_id,city,product_category,product_name,quantity,price,discount_percent,payment_method,rating,returned
0,1,2023-03-13,189,Kolkata,Electronics,Laptop,4,1160,10,Debit Card,5.0,0
1,2,2023-03-29,100,Delhi,Clothing,Jeans,3,37494,10,UPI,3.0,0
2,3,2023-10-04,161,Hyderabad,Electronics,Smartwatch,2,2733,15,UPI,4.0,0
3,4,2024-04-19,59,Delhi,Electronics,Laptop,5,27780,0,Credit Card,2.0,0
4,5,2024-07-20,244,Delhi,Electronics,Smartwatch,4,489,10,Cash on Delivery,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1196,2024-07-13,191,Kolkata,Clothing,Dress,1,26505,10,UPI,NaN,0
1196,1197,2024-02-05,296,Hyderabad,Electronics,Smartphone,4,45832,10,Cash on Delivery,1.0,0
1197,1198,2024-09-24,226,Mumbai,Electronics,Laptop,4,37366,0,Credit Card,2.0,0
1198,1199,2023-08-04,43,Chennai,Home,Mixer,4,39665,15,UPI,3.0,0
1199,1200,2024-01-25,22,Chennai,Sports,Gym Gloves,5,41393,0,Debit Card,1.0,0

In [5]:
# 1 Show the first 10 rows of the orders dataset.
df.head(10)

,order_id,order_date,customer_id,city,product_category,product_name,quantity,price,discount_percent,payment_method,rating,returned
0,1,2023-03-13,189,Kolkata,Electronics,Laptop,4,1160,10,Debit Card,5.0,0
1,2,2023-03-29,100,Delhi,Clothing,Jeans,3,37494,10,UPI,3.0,0
2,3,2023-10-04,161,Hyderabad,Electronics,Smartwatch,2,2733,15,UPI,4.0,0
3,4,2024-04-19,59,Delhi,Electronics,Laptop,5,27780,0,Credit Card,2.0,0
4,5,2024-07-20,244,Delhi,Electronics,Smartwatch,4,489,10,Cash on Delivery,1.0,0
5,6,2023-06-16,274,Chennai,Clothing,Dress,3,41906,20,Debit Card,4.0,1
6,7,2023-12-12,53,Kolkata,Electronics,Smartphone,2,43301,0,Cash on Delivery,2.0,0
7,8,2023-02-04,206,Delhi,Home,Lamp,4,48855,20,Credit Card,1.0,0
8,9,2024-04-21,191,Bangalore,Home,Mixer,4,19757,5,Cash on Delivery,2.0,0
9,10,2023-09-27,271,Pune,Electronics,Headphones,2,37365,15,Debit Card,NaN,0

In [7]:
# 2 Check the shape of the orders dataset.
df.shape

(1200, 12)

In [13]:
#3 Display all column names in the orders dataset.
df.columns

Index(['order_id', 'order_date', 'customer_id', 'city', 'product_category',
       'product_name', 'quantity', 'price', 'discount_percent',
       'payment_method', 'rating', 'returned'],
      dtype='object')

In [15]:
#4 Check the data types of all columns.
df.dtypes

order_id              int64
order_date           object
customer_id           int64
city                 object
product_category     object
product_name         object
quantity              int64
price                 int64
discount_percent      int64
payment_method       object
rating              float64
returned              int64
dtype: object

In [16]:
#5 Find how many missing values exist in each column.
df.fillna

<bound method NDFrame.fillna of       order_id  order_date  customer_id       city product_category  \
0            1  2023-03-13          189    Kolkata      Electronics
1            2  2023-03-29          100      Delhi         Clothing
2            3  2023-10-04          161  Hyderabad      Electronics
3            4  2024-04-19           59      Delhi      Electronics
4            5  2024-07-20          244      Delhi      Electronics
...        ...         ...          ...        ...              ...
1195      1196  2024-07-13          191    Kolkata         Clothing
1196      1197  2024-02-05          296  Hyderabad      Electronics
1197      1198  2024-09-24          226     Mumbai      Electronics
1198      1199  2023-08-04           43    Chennai             Home
1199      1200  2024-01-25           22    Chennai           Sports

     product_name  quantity  price  discount_percent    payment_method  \
0          Laptop         4   1160                10        Debit Card
1           Jeans         3  37494                10               UPI
2      Smartwatch         2   2733                15               UPI
3          Laptop         5  27780                 0       Credit Card
4      Smartwatch         4    489                10  Cash on Delivery
...           ...       ...    ...               ...               ...
1195        Dress         1  26505                10               UPI
1196   Smartphone         4  45832                10  Cash on Delivery
1197       Laptop         4  37366                 0       Credit Card
1198        Mixer         4  39665                15               UPI
1199   Gym Gloves         5  41393                 0        Debit Card

      rating  returned
0        5.0         0
1        3.0         0
2        4.0         0
3        2.0         0
4        1.0         0
...      ...       ...
1195     NaN         0
1196     1.0         0
1197     2.0         0
1198     3.0         0
1199     1.0         0

[1200 rows x 12 columns]>

In [19]:
#6 Show only these columns: order_id, product_name, price, quantity.
df[['order_id', 'product_name', 'price', 'quantity']]

      order_id product_name  price  quantity
0            1       Laptop   1160         4
1            2        Jeans  37494         3
2            3   Smartwatch   2733         2
3            4       Laptop  27780         5
4            5   Smartwatch    489         4
...        ...          ...    ...       ...
1195      1196        Dress  26505         1
1196      1197   Smartphone  45832         4
1197      1198       Laptop  37366         4
1198      1199        Mixer  39665         4
1199      1200   Gym Gloves  41393         5

[1200 rows x 4 columns]

In [24]:
#7 Filter all orders where price is greater than 10,000.
df[df['price']>10000]

,order_id,order_date,customer_id,city,product_category,product_name,quantity,price,discount_percent,payment_method,rating,returned
1,2,2023-03-29,100,Delhi,Clothing,Jeans,3,37494,10,UPI,3.0,0
3,4,2024-04-19,59,Delhi,Electronics,Laptop,5,27780,0,Credit Card,2.0,0
5,6,2023-06-16,274,Chennai,Clothing,Dress,3,41906,20,Debit Card,4.0,1
6,7,2023-12-12,53,Kolkata,Electronics,Smartphone,2,43301,0,Cash on Delivery,2.0,0
7,8,2023-02-04,206,Delhi,Home,Lamp,4,48855,20,Credit Card,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1196,2024-07-13,191,Kolkata,Clothing,Dress,1,26505,10,UPI,NaN,0
1196,1197,2024-02-05,296,Hyderabad,Electronics,Smartphone,4,45832,10,Cash on Delivery,1.0,0
1197,1198,2024-09-24,226,Mumbai,Electronics,Laptop,4,37366,0,Credit Card,2.0,0
1198,1199,2023-08-04,43,Chennai,Home,Mixer,4,39665,15,UPI,3.0,0
1199,1200,2024-01-25,22,Chennai,Sports,Gym Gloves,5,41393,0,Debit Card,1.0,0

In [26]:
#8 Filter orders where city = Bangalore.
df[df['city']=='Bangalore']

,order_id,order_date,customer_id,city,product_category,product_name,quantity,price,discount_percent,payment_method,rating,returned
8,9,2024-04-21,191,Bangalore,Home,Mixer,4,19757,5,Cash on Delivery,2.0,0
11,12,2023-02-10,157,Bangalore,Electronics,Tablet,4,8871,20,Debit Card,5.0,0
33,34,2023-06-09,9,Bangalore,Clothing,Dress,4,21232,20,Debit Card,1.0,0
34,35,2024-09-19,75,Bangalore,Clothing,Shoes,3,4799,0,Debit Card,1.0,0
45,46,2024-09-30,155,Bangalore,Clothing,Jeans,2,7755,5,Debit Card,2.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1155,1156,2024-02-19,93,Bangalore,Clothing,Jeans,1,6573,20,Debit Card,2.0,0
1163,1164,2024-08-24,300,Bangalore,Clothing,Shoes,5,5012,15,Credit Card,4.0,0
1173,1174,2024-11-02,267,Bangalore,Clothing,Shoes,3,18908,15,Credit Card,NaN,0
1182,1183,2023-07-15,29,Bangalore,Home,Cookware,1,31094,5,UPI,2.0,1
1183,1184,2024-02-09,124,Bangalore,Electronics,Smartwatch,5,23632,0,Cash on Delivery,3.0,0

In [29]:
#9 Filter orders where price > 20000 AND quantity >= 2.
df[(df['price']>20000) & (df['quantity']>=2)]

,order_id,order_date,customer_id,city,product_category,product_name,quantity,price,discount_percent,payment_method,rating,returned
1,2,2023-03-29,100,Delhi,Clothing,Jeans,3,37494,10,UPI,3.0,0
3,4,2024-04-19,59,Delhi,Electronics,Laptop,5,27780,0,Credit Card,2.0,0
5,6,2023-06-16,274,Chennai,Clothing,Dress,3,41906,20,Debit Card,4.0,1
6,7,2023-12-12,53,Kolkata,Electronics,Smartphone,2,43301,0,Cash on Delivery,2.0,0
7,8,2023-02-04,206,Delhi,Home,Lamp,4,48855,20,Credit Card,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1192,1193,2024-06-03,275,Pune,Clothing,Dress,4,37576,15,Credit Card,1.0,1
1196,1197,2024-02-05,296,Hyderabad,Electronics,Smartphone,4,45832,10,Cash on Delivery,1.0,0
1197,1198,2024-09-24,226,Mumbai,Electronics,Laptop,4,37366,0,Credit Card,2.0,0
1198,1199,2023-08-04,43,Chennai,Home,Mixer,4,39665,15,UPI,3.0,0
1199,1200,2024-01-25,22,Chennai,Sports,Gym Gloves,5,41393,0,Debit Card,1.0,0

In [35]:
#10 Sort the dataset by price (highest first).
df['price'].sort_values(ascending=False).reset_index()

      index  price
0       911  49923
1       901  49849
2      1016  49838
3       989  49776
4       900  49752
...     ...    ...
1195   1094    511
1196     16    506
1197      4    489
1198    581    436
1199    375    397

[1200 rows x 2 columns]

In [39]:
#11 Find total number of orders per city.
df.groupby('city')['order_id'].count().reset_index()

        city  order_id
0  Bangalore       154
1    Chennai       184
2      Delhi       169
3  Hyderabad       169
4    Kolkata       170
5     Mumbai       172
6       Pune       182

In [42]:
#12 Find number of unique product categories.
df['product_category'].nunique()

4

In [45]:
#13 Find average price of products.
df['price'].mean()

np.float64(24969.635833333334)

In [47]:
#14 Create a new column total_price = price * quantity.
df['total_price']=df['price']*df['quantity']
print(df)

      order_id  order_date  customer_id       city product_category  \
0            1  2023-03-13          189    Kolkata      Electronics
1            2  2023-03-29          100      Delhi         Clothing
2            3  2023-10-04          161  Hyderabad      Electronics
3            4  2024-04-19           59      Delhi      Electronics
4            5  2024-07-20          244      Delhi      Electronics
...        ...         ...          ...        ...              ...
1195      1196  2024-07-13          191    Kolkata         Clothing
1196      1197  2024-02-05          296  Hyderabad      Electronics
1197      1198  2024-09-24          226     Mumbai      Electronics
1198      1199  2023-08-04           43    Chennai             Home
1199      1200  2024-01-25           22    Chennai           Sports

     product_name  quantity  price  discount_percent    payment_method  \
0          Laptop         4   1160                10        Debit Card
1           Jeans         3  37494                10               UPI
2      Smartwatch         2   2733                15               UPI
3          Laptop         5  27780                 0       Credit Card
4      Smartwatch         4    489                10  Cash on Delivery
...           ...       ...    ...               ...               ...
1195        Dress         1  26505                10               UPI
1196   Smartphone         4  45832                10  Cash on Delivery
1197       Laptop         4  37366                 0       Credit Card
1198        Mixer         4  39665                15               UPI
1199   Gym Gloves         5  41393                 0        Debit Card

      rating  returned  total_price
0        5.0         0         4640
1        3.0         0       112482
2        4.0         0         5466
3        2.0         0       138900
4        1.0         0         1956
...      ...       ...          ...
1195     NaN         0        26505
1196     1.0         0       183328
1197     2.0         0       149464
1198     3.0         0       158660
1199     1.0         0       206965

[1200 rows x 13 columns]

In [48]:
#15 Find the maximum product price in the dataset.
df['price'].max()

np.int64(49923)

In [49]:
#16 Find the minimum product price.
df['price'].min()

np.int64(397)

In [54]:
#17 Show all orders where rating is missing.
df['rating'].isna()

0       False
1       False
2       False
3       False
4       False
        ...
1195     True
1196    False
1197    False
1198    False
1199    False
Name: rating, Length: 1200, dtype: bool

In [55]:
#18 Replace missing ratings with 0.
df['rating'].fillna(0)

0       5.0
1       3.0
2       4.0
3       2.0
4       1.0
       ...
1195    0.0
1196    1.0
1197    2.0
1198    3.0
1199    1.0
Name: rating, Length: 1200, dtype: float64

In [58]:
#19 Count how many orders were returned.
df['returned'].value_counts().reset_index()

   returned  count
0         0   1094
1         1    106

In [61]:
# 20 Find top 5 most expensive orders.
df['price'].sort_values(ascending=False).head(5).reset_index()

   index  price
0    911  49923
1    901  49849
2   1016  49838
3    989  49776
4    900  49752